/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const AlarmEvent = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const BloodPressure = IDL.Record({
  'systolic' : IDL.Nat,
  'diastolic' : IDL.Nat,
});
export const HealthMetric = IDL.Record({
  'bloodPressure' : BloodPressure,
  'heartRate' : IDL.Nat,
  'timestamp' : Time,
  'hypertensionRisk' : IDL.Bool,
});
export const MovementAnomaly = IDL.Record({
  'description' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addHealthMetric' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool], [], []),
  'getAlarmEvents' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(AlarmEvent)],
      ['query'],
    ),
  'getHealthMetrics' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(HealthMetric)],
      ['query'],
    ),
  'getMovementAnomalies' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(MovementAnomaly)],
      ['query'],
    ),
  'reportMovementAnomaly' : IDL.Func([IDL.Text], [], []),
  'triggerAlarm' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const AlarmEvent = IDL.Record({ 'message' : IDL.Text, 'timestamp' : Time });
  const BloodPressure = IDL.Record({
    'systolic' : IDL.Nat,
    'diastolic' : IDL.Nat,
  });
  const HealthMetric = IDL.Record({
    'bloodPressure' : BloodPressure,
    'heartRate' : IDL.Nat,
    'timestamp' : Time,
    'hypertensionRisk' : IDL.Bool,
  });
  const MovementAnomaly = IDL.Record({
    'description' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addHealthMetric' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool], [], []),
    'getAlarmEvents' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(AlarmEvent)],
        ['query'],
      ),
    'getHealthMetrics' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(HealthMetric)],
        ['query'],
      ),
    'getMovementAnomalies' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(MovementAnomaly)],
        ['query'],
      ),
    'reportMovementAnomaly' : IDL.Func([IDL.Text], [], []),
    'triggerAlarm' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };