/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AlarmEvent { 'message' : string, 'timestamp' : Time }
export interface BloodPressure { 'systolic' : bigint, 'diastolic' : bigint }
export interface HealthMetric {
  'bloodPressure' : BloodPressure,
  'heartRate' : bigint,
  'timestamp' : Time,
  'hypertensionRisk' : boolean,
}
export interface MovementAnomaly { 'description' : string, 'timestamp' : Time }
export type Time = bigint;
export interface _SERVICE {
  'addHealthMetric' : ActorMethod<[bigint, bigint, bigint, boolean], undefined>,
  'getAlarmEvents' : ActorMethod<[bigint, bigint], Array<AlarmEvent>>,
  'getHealthMetrics' : ActorMethod<[bigint, bigint], Array<HealthMetric>>,
  'getMovementAnomalies' : ActorMethod<
    [bigint, bigint],
    Array<MovementAnomaly>
  >,
  'reportMovementAnomaly' : ActorMethod<[string], undefined>,
  'triggerAlarm' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];